services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"

  db:
    image: "postgres:16-alpine3.23"
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: